steps:
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: IntegServiceKeyCred
    integrationFlowId: IF_CICD_Demo
    integrationFlowName: IF_CICD_Demo
    packageId: CICD_Package_Demo
    filePath: 'CICDPackageDemo_artifacts.zip'
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: IntegServiceKeyCred
    integrationFlowId: IF_CICD_Demo
