steps:
  integrationArtifactUpload:
    cpiApiServiceKeyCredentialsId: IntegServiceKeyCred
    integrationFlowId: <MY_INTEGRATION_FLOW_ID>
    integrationFlowName: <MY_INTEGRATION_FLOW_Name>
    packageId: <MY_INTEGRATION_Package_ID>
    filePath: 'artifacts/your-flow.zip'
  integrationArtifactDeploy:
    cpiApiServiceKeyCredentialsId: IntegServiceKeyCred
    integrationFlowId: <flow-id>
